name: shared_storage
description: "Flutter plugin to work with external storage and privacy-friendly APIs."
version: 0.8.2

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: io.alexrintt.sharedstorage
        pluginClass: SharedStoragePlugin
